version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
      - "80:80"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
