version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    #command: --smallfiles
    volumes:
      - mongodata:/data/db
    networks:
      - main-network
    command: ["--bind_ip", "0.0.0.0"]
  reactive-app:
    build:
      context: Reactive-demo
      dockerfile: Dockerfile
    image: reactive-demo
    container_name: reactive-demo
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - 8082:8082
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
    networks:
      - main-network
  mvc-app:
    build:
      context: Mvc-demo
      dockerfile: Dockerfile
    image: mvc-demo
    container_name: mvc-demo
    restart: on-failure
    depends_on:
      - reactive-app
    ports:
      - 8081:8081
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
    networks:
      - main-network

volumes:
  mongodata:

networks:
  main-network:
    name: network
